base/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('leave_review/', views.leave_review, name='leave_review'),
    path('portfolio/',views.portfolio, name='portfolio')
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('joab/', admin.site.urls),
    path('', include('base.urls')),
    path('resume/', include('resume.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from . import views
from django.urls import path

app_name='resume'
urlpatterns=[
    path('',views.resume, name='resume'),
]

api/models.py
from django.db import models

# Create your models here.

base/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='reviews/', null=True, blank=True)
    position = models.CharField(max_length=50)
    message = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Reviews'
        ordering = ['-date']

class About(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    image = models.ImageField(upload_to='about/', null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'About'

class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name_plural = 'Contact'

projects_experiences/models.py
from django.db import models
# Create your models here.
class Experience(models.Model):
    position = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.position

    class Meta:
        verbose_name_plural = 'Experience'
        ordering = ['-end_date', '-start_date']
    
class Project(models.Model):
    title = models.CharField(max_length=50)
    company = models.CharField(max_length=100)
    image = models.ImageField(upload_to='project/', null=True, blank=True)
    description = models.TextField()
    github_url = models.URLField(max_length=200, blank=True, null=True)
    live_url = models.URLField(max_length=200, blank=True, null=True)
    date_completed = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Projects'
        ordering = ['-date_completed']

resume/models.py
from django.db import models

# Create your models here.
class Education(models.Model):
    course = models.CharField(max_length=100)
    institution = models.CharField(max_length=100)
    institution_url = models.URLField(max_length=200, blank=True, null=True)
    institution_city = models.CharField(max_length=100)
    expected_grad_date = models.DateField(null=True, blank=True)
    date_completed = models.DateField(null=True, blank=True)
    certificate_url = models.URLField(max_length=300, blank=True, null=True)
    related_course_work = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.course

    class Meta:
        verbose_name_plural = 'Education'
        ordering = ['-date_completed', '-expected_grad_date']

class Referees(models.Model):
    name = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Referees'
        ordering = ['-created']

skills/models.py
from django.db import models

# Create your models here.
choices = (
        ('Beginner', 'Beginner'),
        ('Intermediate', 'Intermediate'),
        ('Advanced', 'Advanced'),
    )
class ProgrammingLanguage(models.Model):
    title = models.CharField(max_length=50)
    level = models.CharField(max_length=50, default='Beginner', choices=choices)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Programming Languages'
        ordering = ['level']
class Framework(models.Model):
    title = models.CharField(max_length=50)
    level = models.CharField(max_length=50, default='Beginner', choices=choices)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Frameworks'
        ordering = ['level']

class Tool(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Tools'

api/views.py
from django.shortcuts import render

# Create your views here.

base/views.py
from django.shortcuts import render, redirect
from .models import Review, About, Contact
from projects_experiences.models import Project
from django.contrib import messages
# Create your views here.
def index(request):
    reviews = Review.objects.all()
    context = {
        'reviews': reviews,
    }
    return render(request,'index.html', context)

def contact(request):
    if request.method == 'POST':
        fname = request.POST['fname']
        lname = request.POST['lname']
        email = request.POST['email']
        message = request.POST['message']

        if len(message) < 10:
            messages.warning(request, "Feedback length should be greator than 10 characters")
            return redirect('contact')
        
        feed = Contact.objects.create(
            first_name=fname,
            last_name=lname,
            email = email,
            message = message
        )
        feed.save()

        print(f"\n\n {fname} {lname} \n\n {email} \n\n {message} \n\n")
        messages.success(request,"Message sent successfully")
        return redirect('/')
    
    return render(request, 'contact.html')

def about(request):
    about = About.objects.all()
    context = {
        'about': about,
    }
    return render(request, 'about.html', context)

def leave_review(request):
    if request.method == 'POST' and request.FILES:
        name = request.POST['name']
        position = request.POST['position']
        review = request.POST['review']
        image = request.FILES['image']

        if len(review) < 15:
            messages.warning(request, "Feedback length should be greator than 15 characters")
            return redirect('leave_review')

        review = Review.objects.create(
            name=name,
            position=position,
            message = review,
            image=image
        )

        messages.success(request,"Review sent successfully,  Thank you for the Review")
        return redirect('/')
        
    return render(request, 'leave_review.html')


# Create your views here.
def portfolio(request):
    portfolios = Project.objects.all()
    context = {
        'portfolios': portfolios,
    }
    return render(request, 'portfolio.html', context)

resume/views.py
from django.shortcuts import render
from resume.models import Education, Referees
from skills.models import ProgrammingLanguage, Framework, Tool
from projects_experiences.models import Project, Experience
# Create your views here.
def resume(request):

    education = Education.objects.all()
    p_languages = ProgrammingLanguage.objects.all()
    frameworks = Framework.objects.all()
    tools = Tool.objects.all()
    projects = Project.objects.all()
    experiences = Experience.objects.all()
    referees = Referees.objects.all()
    context = {
        'education' : education,
        'p_languages' : p_languages,
        'frameworks' : frameworks,
        'tools' : tools,
        'projects' : projects,
        'experiences' : experiences,
        'referees' : referees,
    }
    return render(request, 'resume.html', context)

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
<h1 class="fw-bold text-secondary mt-5 text-center">About Me</h1>
{% if about %}
    {% for abt in about %}
        <section class="pb-5" id="background">
            <div class="container py-3 shadow-sm">
                <div class="row justify-content-center align-items-center">
                    {% if abt.image %}
                        <div class="col-md-4">
                            <img src="{{ abt.image.url }}" class="img-fluid" alt="{{abt.title}}">
                        </div>
                    {% endif %}
                    <div class="col-md-8">
                        <h2 class="fw-bold text-secondary mt-5">{{ abt.title }}</h2>
                        <p class="text-secondary">{{ abt.description|linebreaks}}</p>
                    </div>
                </div>
            </div>
        </section>
    {% endfor %}
{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="Jeff Odhiambo">
    <meta name="keywords" content="Homepage,Jeff, Odhiambo, Jeff Odhiambo, Portfolio, Resume, CV">
    <meta name="description" content="Jeff Odhiambo's Homepage that contains the overview of his experiences, background and education">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% include 'partials/style.html' %}
    <title>Jeff Odhiambo | {% block title %} {% endblock %}</title>
</head>
<body style="/*background: url(&quot;design.jpg&quot;);*/background-position: 0 -60px;">
    {% include 'partials/top-nav.html' %}
    <div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="text-center my-3 mx-5 alert alert-{{ message.tags }}" role="alert">
                {{message}}
            </div>
        {% endfor %}
    {% endif %}
    </div>
    {% block content %}

    {% endblock %}
    {% include 'partials/footer.html' %}
    {% include 'partials/js.html' %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Contacts{% endblock %}

{% block content %}
<h1 class="fw-bold text-secondary mt-3 mb-4 text-center">Contacts</h1>
<section class="position-relative py-5">
    <div class="d-md-none"><iframe allowfullscreen="" frameborder="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.06403683054!2d37.008411915330576!3d-1.1141283357782634!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f47952563285d%3A0x70d092fb85ccb757!2sVSTech%20Limited%20Company!5e0!3m2!1sen!2ske!4v1663516243533!5m2!1sen!2ske" width="100%" height="100%"></iframe></div>
    <div class="d-none d-md-block position-absolute top-0 start-0 w-100 h-100"><iframe allowfullscreen="" frameborder="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3989.06403683054!2d37.008411915330576!3d-1.1141283357782634!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f47952563285d%3A0x70d092fb85ccb757!2sVSTech%20Limited%20Company!5e0!3m2!1sen!2ske!4v1663516243533!5m2!1sen!2ske" width="100%" height="100%"></iframe></div>
    <div class="position-relative mx-2 my-5 m-md-5">
        <div class="container-fluid position-relative">
            <div class="row">
                <div class="col-md-6 col-xl-5 col-xxl-3 offset-md-6 offset-xl-7 offset-xxl-8">
                    <div>
                        <form class="border rounded shadow p-3 p-md-4 p-lg-5" method="post" style="background: var(--bs-body-bg);">
                            {% csrf_token %}
                            <h3 class="text-center mb-3">Contact me</h3>
                            <div class="d-flex p-2 justify-content-evenly">
                                <a href="tel:+254795067776" class="text-white m-1">
                                    <div class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block bs-icon">
                                       <i class="fa fa-phone" aria-hidden="true"></i>
                                    </div>
                                </a>
                                <a href="mailto:info@odhiambo-jeff.me" class="text-white m-1">
                                    <div class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block bs-icon">
                                       <i class="fa fa-envelope" aria-hidden="true"></i>
                                    </div>
                                </a>
                                <a href="https://www.linkedin.com/in/jeff-odhiambo/" class="text-white m-1">
                                    <div class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block bs-icon">
                                       <i class="fab fa-linkedin" aria-hidden="true"></i>
                                    </div>
                                </a><a href="https://github.com/killall-nano/" class="text-white m-1">
                                    <div class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block bs-icon">
                                       <i class="fab fa-github" aria-hidden="true"></i>
                                    </div>
                                </a>
                                <a href="http://odhiambo-jeff.me" class="text-white m-1">
                                    <div class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block bs-icon">
                                       <i class="fab fa-internet-explorer" aria-hidden="true"></i>
                                    </div>
                                </a>
                                <a href="https://goo.gl/maps/4seLaPrLG9YpHrBi7" class="text-white m-1">
                                    <div class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex flex-shrink-0 justify-content-center align-items-center d-inline-block bs-icon">
                                       <i class="fas fa-map-pin fa-lg fa-fw" aria-hidden="true"></i>
                                    </div>
                                </a>
                            </div>
                            <div class="mb-3">
                                <input class="form-control rounded-pill" type="text" id="fname" name="fname" placeholder="Firstname">
                            </div>
                            <div class="mb-3">
                                <input class="form-control rounded-pill" type="text" id="lname" name="lname" placeholder="Lastname">
                            </div>
                            <div class="mb-3">
                                <input class="form-control rounded-pill" type="email" id="email" name="email" placeholder="Email">
                            </div>
                            <div class="mb-3">
                                <textarea class="form-control" id="message" name="message" rows="6" placeholder="Message"></textarea>
                            </div>
                            <div>
                                <button class="btn btn-primary shadow d-block w-100" type="submit">Send </button>
                            </div>
                        </form>
                    </div>
                </div>      
            </div>
        </div>
    </div>
</section>
  {% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Homepage{% endblock %}

{% block content %}
{% include 'partials/profile.html' %}
<section>
    <div class="container py-5"><div class="mx-auto" style="max-width: 900px;">
        <div class="row row-cols-1 row-cols-md-2 d-flex justify-content-center">
            <div class="col mb-4">
                <div class="card bg-primary-light">
                    <div class="card-body text-center px-4 py-5 px-md-5">
                        <p class="fw-bold text-primary card-text mb-2">Multi-System(SmartTech)</p>
                        <h5 class="fw-bold card-title mb-3">It contains E-School, ECommerce, Blogging, Voting, and CV-Generator</h5>
                        <a href="https://whispering-bayou-71399.herokuapp.com/" class="btn btn-primary btn-sm nav-link text-white">view</a>
                    </div>
                </div>
            </div>
            <div class="col mb-4">
                <div class="card bg-secondary-light">
                    <div class="card-body text-center px-4 py-5 px-md-5">
                        <p class="fw-bold text-secondary card-text mb-2">Church-System(ARS)</p>
                        <h5 class="fw-bold card-title mb-3">Manages church resources, events and users</h5>
                        <a href="http://20.196.152.132/" class="btn btn-secondary btn-sm nav-link text-white">view</a>
                    </div>
                </div>
            </div>
            <div class="col mb-4">
                <div class="card bg-info-light">
                    <div class="card-body text-center px-4 py-5 px-md-5">
                        <p class="fw-bold text-info card-text mb-2">Photography(Donmax)</p>
                        <h5 class="fw-bold card-title mb-3">Manages Media(Photos & Videos), occassions, appointments etc</h5>
                        <a href="http://20.196.152.132:8000/" class="btn btn-info btn-sm nav-link text-white">view</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
<section class="py-5 mt-5">
    <div class="container py-5">
        <div class="row mb-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h2 class="fw-bold"><strong>What People Say About Me</strong></h2>
                <p class="text-muted w-lg-50">No matter the design, logic or project, I can handle it.&nbsp;</p>
            </div>
        </div>
        {% if reviews %}
        <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 d-sm-flex justify-content-sm-center">
            {% for review in reviews %}
            <div class="col mb-4">
                <div class="d-flex flex-column align-items-center align-items-sm-start">
                    <p class="bg-light border rounded border-light small p-4">{{review.message|truncatechars:100}}</p>
                    <div class="d-flex">
                        <img class="rounded-circle flex-shrink-0 me-3 fit-cover" width="50" height="50" src="{% if review.image %}{{review.image.url}}{% else %}{% static 'assets/img/products/1.png' %}{% endif %}">
                        <div>
                            <p class="fw-bold text-primary mb-0">{{review.name}}</p>
                            <p class="text-muted mb-0">{{review.position}}</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <a href="{% url 'leave_review' %}" class="nav-link mt-4 text-secondary fw-bold"><p class="text-center">Leave a review</p></a>
    </div>
</section>
{% endblock %}

templates/leave_review.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Leave a Review{% endblock %}
{% block content %}

<section class="py-5" id="leave-review">
    <div class="container py-5">
        <div class="row mb-4 mb-lg-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <p class="fw-bold text-success mb-2">Leave a Review</p>
                <h3 class="fw-bold">Leave a Review</h3>
            </div>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row justify-content-center">
            <div class="form-group col-md-4">
                    <label for="name" class="fw-bold">Name</label>
                    <input type="text" class="form-control" id="name" name="name" required placeholder="e.g Jeff Odhiambo">
                </div>
                <div class="form-group col-md-4">
                    <label for="position" class="fw-bold">Position</label>
                    <input type="text" class="form-control" id="position" required name="position" placeholder="e.g Android Developer">
                </div>
                <div class="form-group col-md-8 mb-4">
                    <label for="image" class="fw-bold">Profile</label>
                    <input type="file" class="form-control" name="image" required id="image">
                </div>
                <div class="form-group col-md-8">
                    <label for="review" class="fw-bold">Review</label>
                    <textarea class="form-control" id="review" required name="review" rows="3"></textarea>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-8 mt-4">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
           </div>
        </form>
    </div>
</section>
{% endblock %}

templates/partials/footer.html
{% load static %}
<footer class="bg-primary-gradient">
    <div class="container py-4 py-lg-5">
        <div class="row justify-content-center">
            <div class="col-sm-6 col-md-4 text-center text-lg-start d-flex flex-column item">
                <h3 class="fs-6 fw-bold">Services</h3>
                <ul class="list-unstyled">
                    <li>Web design</li>
                    <li>Development</li>
                    <li>Deployment</li>
                    <li>Hosting</li>
                </ul>
            </div>
            <div class="col-sm-6 col-md-5 text-center text-lg-start d-flex flex-column item">
                <h3 class="fs-6 fw-bold">About</h3>
                <ul class="list-unstyled">
                    <li><a href="{% url 'about' %}#background">Background</a></li>
                    <li><a href="{% url 'about' %}#motives">Objectives</a></li>
                    <li><a href="{% url 'about' %}#experience">Experiences</a></li>
                    <li><a href="{% url 'leave_review' %}">Leave a Review</a></li>
                </ul>
            </div>
            <div class="col-lg-3 text-center text-lg-start d-flex flex-column align-items-center order-first align-items-lg-start order-lg-last item social">
                <div class="fw-bold d-flex align-items-center mb-2">
                    <span class="bs-icon-sm bs-icon-circle ml-2">
                        <img src="{% static 'img/JO logo.png' %}" alt="Logo" height="60">
                    </span>
                </div>
                <p class="text-muted copyright">Self driven, hardworking full-stack developer.</p>
            </div>
        </div>
        <hr>
        <div class="text-muted d-flex justify-content-between align-items-center pt-3">
            <p class="mb-0"><a href="http://vstech.live" class="text-muted nav-link">&copy;vstech limited 2022</a></p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item"><a href="mailto:info@odhiambo-jeff.me"><i class="fab fa-google" aria-hidden="true"></i></a></li>
                <li class="list-inline-item"><a href="https://www.linkedin.com/in/jeff-odhiambo/"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                <li class="list-inline-item"><a href="https://github.com/smartjef"><i class="fab fa-github-alt" aria-hidden="true"></i></a></li>
                <li class="list-inline-item"><a href="https://twitter.com/Jeff18309725"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </div>
</footer>

templates/partials/js.html
{% load static %}

<script src="{% static 'assets/bootstrap/js/bootstrap.min.js'  %}"></script>
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/script.min.js' %}"></script>
<script src="{% static 'assets/all.js' %}"></script>

templates/partials/profile.html
{% load static %}
<section>
    <div class="container">
        <div class="row align-items-center justify-content-center" style="min-height: 85vh;">
            <div class="col-md-6">
                <img src="{% static 'img/jeff.png' %}" alt="Jeff Odhiambo" class="img-fluid">
            </div>
            <div class="col-md-6 px-5 text-dark">
                <h1 class="text-primary font-weight-bold">Jeff Odhiambo</h1>
                <h2>Full-Stack Developer</h2>
                <h3 class="mt-3">Contacts:</h3>
                <div class="row">
                    <a href="mailto:info@odhiambo-jeff.me">info@odhiambo-jeff.me</a>
                    <a href="tel:+254795067776">+254795067776</a>
                    <a href="http://odhiambo-jeff.me">odhiambo-jeff.me</a>
                </div>
                <ul class="list-inline mb-0">
                    <li class="list-inline-item"><a href="mailto:info@odhiambo-jeff.me"><i class="fab fa-google" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="https://www.linkedin.com/in/jeff-odhiambo/"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="https://github.com/smartjef"><i class="fab fa-github-alt" aria-hidden="true"></i></a></li>
                    <li class="list-inline-item"><a href="https://twitter.com/Jeff18309725"><i class="fab fa-twitter" aria-hidden="true"></i></a></li>
                </ul>
                <div class="d-flex my-3 align-items-center">
                    <div><a href="{% static 'assets/JEFF ODHIAMBO - FULL STACK DEVELOPER.pdf' %}" download class="btn btn-primary btn-sm rounded-pill m-2">CV</a></div>
                    <div><a href="{% url 'resume:resume' %}" class="btn btn-success btn-sm rounded-pill">Resume</a></div>
                    <div><a href="{% url 'portfolio' %}" class="btn btn-outline-primary rounded-pill btn-sm m-2">Portfolio</a></div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/partials/style.html
{% load static %}
<link rel="shortcut icon" href="{% static 'img/JO logo.png' %}" type="image/x-icon">
<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/all.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">

templates/partials/top-nav.html
{% load static %}
<nav class="navbar navbar-light navbar-expand-md sticky-top navbar-shrink py-3" id="mainNav">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="/">
            <span class="bs-icon-sm bs-icon-circle ml-2">
                <img src="{% static 'img/JO logo.png' %}" alt="Logo" height="60">
            </span>
        </a>
        <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navcol-1">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About me</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contacts</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'resume:resume' %}">Resume</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'portfolio' %}">Portfolio</a></li>
            </ul><a class="btn btn-primary shadow" role="button" href="mailto:info@odhiambo-jeff.me">Hire me</a>
        </div>
    </div>
</nav>